[versions]
agp = "8.13.2"
kotlin = "2.3.0"
serialization = "1.9.0"
lifecycle = "2.10.0"
biometric = "1.4.0-alpha05"
activity = "1.12.2"

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version = "1.17.0" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.9.6" }
junit = { module = "junit:junit", version = "4.13.2" }
junit-ext = { module = "androidx.test.ext:junit", version = "1.3.0" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.7.0" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
activity = { module = "androidx.activity:activity", version.ref = "activity" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.2.1" }
material = { module = "com.google.android.material:material", version = "1.13.0" }
compose-bom = { module = "androidx.compose:compose-bom", version = "2025.12.01" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-material3 = { module = "androidx.compose.material3:material3" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version = "1.2.0" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
biometric-compose = { module = "androidx.biometric:biometric-compose", version.ref = "biometric" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
